### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-mi-flora-care

### ISSUE THREAD

**Issue by bondskin** [oretman/homebridge-mi-flora-care#7]
**Describe The Bug:**
Error: The module '/usr/lib/node_modules/homebridge-mi-flora-care/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires

**To Reproduce:**
restart of HB

**Expected behavior:**
no error message

**Logs:**

Error: The module '/usr/lib/node_modules/homebridge-mi-flora-care/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by Novi001** [comment]
Hello,

reinstall the plugin without delete the config. (remove -> restart -> install -> restart) I think in past, that was the solution for me.

bg
Novi

**Comment by bondskin** [comment]
thanks @Novi001 , that did the trick
